version: 2
jobs:

  build-one:
    docker:
      - image: ubuntu:18.04 # it is faster, do not support sudo? 

    steps:
      - checkout
      - run: echo "A first hello"
      - run:
          name: Performing 'apt-get update'
          command: 'apt-get update'
      - run: 
          name: Installing SUDO    
          command: 'apt-get install -y sudo'    
      - run:
          name: Installing GCC
          command: 'apt-get install -y gcc g++'

    test:
      pre:
        - gcc --version
        - g++ --version
        - make    

  build-two:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true    # default - false
      # Note: You must open a support ticket to have a CircleCI Sales representative enable 
      # Docker Layer Caching on your circleci.com account for an additional fee. 
      # DLC is available by default for CircleCI installations hosted in your own datacenter
      # or private cloud

    #docker:
    #  - image: ubuntu:18.04
    #docker_layer_caching: true    # default - false

    #dependencies:
    #    pre:
    #      - sudo apt-get -y update

    steps:
      - checkout

     # - run:
     #     name: Performing 'apt-get update'
     #     command: 'apt-get update'
     # - run: 
     #     name: Installing SUDO    
     #     command: 'apt-get install -y sudo'
      - run:
          name: Installing GCC
          command: 'sudo apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'sudo apt-get install -y cmake'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'
      - run:
          name: Point Unit Testing
          command: './bin/pointTest.x'
     
     # test:
       # pre:
      #   - gcc --version
       #  - g++ --version
        # - make    

workflows:
  version: 2
  build_one_and_two:
     jobs:
       - build-one
       - build-two